### ISSUE TITLE
Model is only valid from Tue Dec 20 2019 to Tue Dec 10 2024

### ISSUE THREAD

**Issue by diego-betto** [naturalatlas/geomagnetism#8]
Hi,

today our app crashed with the message 
"Model is only valid from Tue Dec 20 2019 to Tue Dec 10 2024"

How can we update the model or disable this error?

Thank you!

**Comment by diego-betto** [comment]
Also please: warn that there is a time limit :)

**Comment by joshuagoran** [comment]
my org would also love to see this model updated, and going forward, politely request that errors are logged rather than crashing with the expired model error 🙏 

to anyone else needing a stopgap, I found and successfully used the fork https://github.com/cristianob/geomagnetism as a replacement

**Comment by diego-betto** [comment]
As a workaround, we have cloned the module and changed the expiry date.
https://github.com/naturalatlas/geomagnetism/blob/master/data/wmm-2020.json#L379

Let's see if the maintainer responds :)

**Comment by facetious** [comment]
This is a bug in implementation rather than outdated spec.

> Please note: The World Magnetic Model 2025 will be released on December 17, 2024.
> The model is produced at 5-year intervals, with the current model expiring on December 31, 2024.
> _Source: https://www.ncei.noaa.gov/products/world-magnetic-model_

Hopefully the updated spec is integrated soon after it is released, as well.

**Comment by diego-betto** [comment]
Nice catch! Thanks @facetious 
Hopefully waiting :)

**Comment by alist** [comment]
Wonderful little y2k-style surprise here :) 

If you can wait for the full fix...

```ts
  const magneticFieldInfo = geomagnetism
    .model(new Date(2024, 11, 9))
    .point([vehicleWaypoint.latitudeDeg, vehicleWaypoint.longitudeDeg]);
```

**Comment by cristianob** [comment]
NOAA will release the next World Magnetic Model on December 17th.

Until this date, we need to use the outdated model. My fork will only log a error instead of crashing as a temporary replacement.
https://github.com/cristianob/geomagnetism

Just do a
`$ npm install @cristianob/geomagnetism --save`

And change the imports to
`import Geomagnetism from '@cristianob/geomagnetism'`

On December 17th, I will release a new version on my fork and submit a PR here. I am hoping the author will update this library.

If the author don't update, I will mantain the library updated on my fork.
PS: My fork has a typescript typing that I will send a PR here too.

**Comment by cristianob** [comment]
> NOAA will release the next World Magnetic Model on December 17th.
> 
> Until this date, we need to use the outdated model. My fork will only log a error instead of crashing as a temporary replacement. https://github.com/cristianob/geomagnetism
> 
> Just do a `$ npm install @cristianob/geomagnetism --save`
> 
> And change the imports to `import Geomagnetism from '@cristianob/geomagnetism'`
> 
> On December 17th, I will release a new version on my fork and submit a PR here. I am hoping the author will update this library.
> 
> If the author don't update, I will mantain the library updated on my fork. PS: My fork has a typescript typing that I will send a PR here too.

@diego-betto

**Comment by cristianob** [comment]
**Update**
My fork was updated with the new WMM2025 model. Will submit a PR to this repo too. 

@facetious @diego-betto

**Comment by brianreavis** [comment]
@cristianob Thanks for taking this on! I'll keep an eye out for the PR and will get it merged and released pronto.

Regarding logging versus throwing: The readme should be updated to make the current error behavior clear (showing that one should wrap the operation with a try/catch). I don't think returning results outside the model bounds is an appropriate behavior, as that could be dangerous for navigational applications. Logging an error to stderr isn't sufficient because it could be missed for years when running on a server.

If an out-of-bounds value is really desired, I could see attaching it to the thrown error as an escape hatch (`err.result`).

**Comment by cristianob** [comment]
@brianreavis PR #9 sent

I made some architectural decisions addind a should_throw (default = true) and update the readme, as some users complain about apps crashing when model expires.

Please, feel free to reach me if you have any questions.

**Comment by brianreavis** [comment]
Fixed by https://github.com/naturalatlas/geomagnetism/pull/9 (now out on npm: [0.2.0](https://www.npmjs.com/package/geomagnetism/v/0.2.0))
